<?php
/**
 * Configuration file.
 *
 * Rename to config.php if you want to use it.
 * If you use this as a Wordpress-plugin together with !THE MASTER
 * config.php will have no affect once you saved the configuration in the plugin screen.
 *
 * @category Markup
 * @package  Xiphe\HTML
 * @author   Hannes Diercks <xiphe@gmx.de>
 * @license  http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE
 * @link     https://github.com/Xiphe/-HTML/blob/master/HTML.php
 */

namespace Xiphe\HTML;

$config = array(
    /*
     * Base URI
     *
     * Used to replace ./ in src & href if MagicURI is enabled.
     * Default: "./"
     */
    'baseUrl' => "./",

    /*
     * Disable comments
     *
     * No <!-- comments --> will be generated by HTML.
     * Default: false
     */
    'noComments' => false,

    /*
     * Enable MagicURI
     *
     * Will replace ./ in src and href attributes by the Base URI
     * Default: true
     */
    'magicUrl' => true,

    /*
     * Disable HTML
     *
     * No generation of HTML Tags.
     * Default: false
     */
    'disable' => false,

    /*
     * Clean Wordpress output
     *
     * Cleans up things like the wp_head.
     * Default: true
     */
    'cleanwpoutput' => true,

    /*
     * Translator
     *
     * Default callback that handles the translation of content.
     * Default: "__"
     */
    'translator' => "__",

    /*
     * Textdomain
     *
     * Default textdomain. Used to identify the script that initiates the translation.
     * Default: "html"
     */
    'textdomain' => "html",

    /*
     * Starting tabcount
     *
     * This is the indention-level the document will start with.
     * Default: 0
     */
    'tabs' => 0,

    /*
     * Tab-symbol
     *
     * The string that is used for indenting new lines.
     * Default: "\t"
     */
    'tab' => "\t",

    /*
     * Line-break-symbol
     *
     * The string that is used to break the current line.
     * Default: "\n"
     */
    'break' => "\n",

    /*
     * Debug
     * 
     * Default: "disabled"
     */
    'debug' => "disabled",

    /*
     * Store
     *
     * Default storage method for started tags.
     * Default: "global"
     */
    'store' => "global",

    /*
     * Tab-worth
     *
     * How much spaces is the worth of the 'tab' setting.
     * Default: 4
     */
    'tabWorth' => 4,

    /*
     * Maximal line width
     *
     * Maximum count of letters per line. Used by strong cleaning mode.
     * Default: 140
     */
    'maxLineWidth' => 140,

    /*
     * Maximal line width
     *
     * Minimum count of letters per line. Used by strong cleaning mode.
     * Default: 50
     */
    'minLineWidth' => 50,

    /*
     * Clean
     *
     * If true the content of every tag will be cleaned up.
     * Default: false
     */
    'clean' => false,

    /*
     * Clean-mode
     *
     * What kind of cleaning should be used? Strong looks better and takes longer :)
     * Default: "basic"
     */
    'cleanMode' => "basic"
);