<?php
$name = 'Basic tag';
$order = 10;
$tags = 'tag basic';

$description = <<<'EOD'
Every **Tag** will be generated by a **method** call of the $HTML object, the 
tagname is the method name.
EOD;

$code = <<<'EOD'
$HTML->div('this is a basic div');
EOD;

$prediction = <<<'EOD'
<div>this is a basic div</div>

EOD;
?>