<?php
$name = 'c for Clean Content';
$order = 110;
$tags = 'tag options, options, tag, clean';

$description = <<<'EOD'
When the tags content contains html markup it can be parsed to fit into the
output generated by html.  
See [cleanMode Settings](#cleanmode) for more informations.

Cleaning the content has a **strong impact in performance**. *Use it wisely.*  
Strong cleaning also cleans up misspelled closing tags. (See ul + ol in example)
EOD;

$code = <<<'EOD'
$markup = '<div id="foo"><ul><li>A</li><li>B</li><li>C</li></ol>
Lorem Ipsum</div>';
$CleaningHTML = new Xiphe\HTML(array(
	'tabs' => 0,
	'cleanMode' => 'strong'
));
$HTML->div($markup, '#wrap'); // no cleaning.

$HTML->n();

$HTML->c_div($markup, '#wrap'); // basic cleaning (default)

$HTML->n();

$CleaningHTML->c_div($markup, '#wrap'); // strong cleaning
EOD;

$prediction = <<<'EOD'
<div id="wrap">
	<div id="foo"><ul><li>A</li><li>B</li><li>C</li></ol>
Lorem Ipsum</div>
</div><!-- #wrap -->

<div id="wrap">
	<div id="foo"><ul><li>A</li><li>B</li><li>C</li></ol>
	Lorem Ipsum</div>
</div><!-- #wrap -->

<div id="wrap">
	<div id="foo">
		<ul>
			<li>A</li>
			<li>B</li>
			<li>C</li>
		</ul>
		Lorem Ipsum
	</div><!-- #foo -->
</div><!-- #wrap -->

EOD;
?>